### ISSUE TITLE
Page structure for location button selections

### ISSUE THREAD

**Issue by gavin-asay** [daniwhitlock/Cravings#4]
When a user searches for a location, Zamato API will list ten matches and the user will need to narrow it down to the correct one. I've made buttons for each match that I've stuck under the Top Restaurants header. We'll need to figure out the best place for those. (In a modal, maybe?)

**Comment by lexiehansen** [comment]
created modal that opens upon click of the submit buttons in the restaurants card, placeholder buttons now populate in the modal. Not yet functional.
